### ISSUE TITLE
Pluggin not working since 08 august 2020

### ISSUE THREAD

**Issue by froglock30** [bitcanon/visonicalarm#1]
Hi,

It seem that the rest API is not available anymore. New visonic Go android APK is now asking a registration (mail / password) et there is a crypted communication between server and app.

I tried to trace TCP flow using wireshard and android emulator and API command are now crypted and it's way too complicated for me.

If you still use Visonic and can look at this new API, I would be happy to help.

Regards,

Fred.

**Comment by Julien-Roger** [comment]
Someone did the job:
https://github.com/And3rsL/VisonicAlarm2

Not tried yet

**Comment by bitcanon** [comment]
Hi, yes I'm still using Visonic and has not been having any problems at all. I never use the app anymore, just controlling the alarm system via scripts and home automation integration.

I will though try out the Visonic Go app and se what has changed.

**Comment by bitcanon** [comment]
> Someone did the job:
> https://github.com/And3rsL/VisonicAlarm2
> 
> Not tried yet

Until my alarm company update to this new API, your best bet is to use this repository instead.
As of now I only has access to the API versions 3 and 4. But will sure look into updating when I have a newer version of the API to develop against.

**Comment by froglock30** [comment]
Hi, for now, i use an hardware solution (fibaro zwave sensor) on pgm exit but stay connected to you pluggin to keep informed of future evolutions :)

**Comment by bitcanon** [comment]
Hi, nice that you found a workaround. What kind of information are you getting from the Fibaro sensor? Are you able to arm and disarm the alarm system as well?
It looks like @And3rsL has managed to connect to version 8.0 of the API. I might have a look and see if I can extend my code to support both version 4.0 and 8.0. When I have the time :)
@froglock30: Would you be willing to try out the library if I add support for version 8.0?

**Comment by bitcanon** [comment]
> Hi, for now, i use an hardware solution (fibaro zwave sensor) on pgm exit but stay connected to you pluggin to keep informed of future evolutions :)

Hi, hope you're doing great. Just want to inform you that the future has arrived 😉 (I now support API version 9.0)
