### ISSUE TITLE
KeyError exception when connecting to API v8.0

### ISSUE THREAD

**Issue by bitcanon** [bitcanon/visonicalarm#19]
First of all thank you and congratulate you for your work with this library to connect to visonic, my name is Dario, nice to meet you.
 
I'm trying to connect to my alarm, I have visonic-go and all the parameters are well configured but I don't know why it fails and I don't know how to debug the library.
 
My provider's API version is 8.0, my company's panel_id is a 6-digit decimal value and not a hexadecimal value, and the endpoint I'm trying to connect to is (www.visonic.xxx.com) and the error that I get using your example script (with all the parameters correctly set) is this:
 
```
Connecting to 'www.visonic.biservicus.com'... 
Supported REST API version(s): 8.0 
Enter your master code: 
Authenticating using 'myemail@email.com'... 
Successfully authenticated. 

Traceback (most recent call last): File
"/home/user123/Delete/visonicAlarm/alarm.py", line 213, in <module> main() File
"/home/user123/Delete/visonicAlarm/alarm.py", line 168, in main if notconnect(): File
"/home/user123/Delete/visonicAlarm/alarm.py", line 124, in connect if not alarm.connected(): File 
"/home/user123/.local/lib/python3.10/site-packages/visonic/alarm.py", line 56, in connected return self.get_status().connected 
File "/home/user123/.local/lib/python3.10/site-packages/visonic/alarm.py", line 344, in get_status 
bba_connected=status['connected_status']['bba']['is_connected'], KeyError: 'bba'
```
 
Thank you very much, I hope your answer.

**Comment by bitcanon** [comment]
Hi, and thanks for your input.

Can you edit the file `/home/user123/.local/lib/python3.10/site-packages/visonic/alarm.py` and add a simple `print(status)` on line 328 in that file:

```python
...
...
def get_status(self):
        """ Fetch the current state of the alarm system. """

        status = self.__api.get_status()

        print(status) # <==== Add this line (around line 328)

        partition_list = []

        # Create the partitions
        for partition in status['partitions']:
            new_part = Partition(
                id=partition['id'], 
                state=partition['state'], 
                status=partition['status'], 
                ready=partition['ready'], 
                options=partition['options'],
            )
            partition_list.append(new_part)
...
...
```
Then run your test script again and give me the output of the `print`-statement. Should be something like:
```python
{'connected': True, 'connected_status': {'bba': {'is_connected': True, 'state': 'online'}, 'gprs': {'is_connected': False, 'state': 'online'}}, 'discovery': {'completed': True, 'stages': 11, 'in_queue': 0, 'triggered': None}, 'partitions': [{'id': -1, 'state': 'HOME', 'status': '', 'ready': True, 'options': []}], 'rssi': {'level': 'good', 'network': 'Unknown'}}
```

Let me know how it goes! 😄

**Comment by PhillipMC** [comment]
thanks for your answer, the output of print is:
`{'connected': False, 'connected_status': {'gprs': {'is_connected': False, 'state': 'online'}}, 'discovery': {'completed': True, 'stages': 10, 'in_queue': 0, 'triggered': None}, 'partitions': [{'id': -1, 'state': 'DISARM', 'status': '', 'ready': True, 'options' : []}], 'rssi': {'level': 'ok', 'network': 'Unknown'}}`

**Comment by bitcanon** [comment]
I have now updated the library to version 3.12.0 which should handle the exception you get.
The reason for the exception being raised seems to be that you don't have an ethernet module installed in your alarm panel and I'm not sure how the rest of the library will react to that, but you will see 😄

**Comment by PhillipMC** [comment]
Thank you very much, I already have it implemented, I was testing the features and it works perfectly, thanks for the library and the help :+1:
